use crate::ast::*;
use crate::token::Span;
use std::collections::HashSet;

pub struct CppGenerator {
    output: String,
    indent_level: usize,
    dispatch_needed: HashSet<String>,
    return_trait: Option<String>,  // current function's return trait name
}

impl CppGenerator {
    pub fn new() -> Self {
        Self { output: String::new(), indent_level: 0, dispatch_needed: HashSet::new(), return_trait: None }
    }

    pub fn generate(mut self, module: &Module) -> String {
        self.emit_header();
        self.emit_module(module);
        self.emit_dispatch_wrappers();
        self.output
    }

    fn emit_dispatch_wrappers(&mut self) {
        for name in self.dispatch_needed.clone() {
            self.emitln(&format!("static std::unordered_map<uint64_t, int(*)(Matrix&,Matrix&)> _t_{0};", name));
            self.emitln(&format!("static struct {{ uint64_t k=UINT64_MAX; int(*fn)(Matrix&,Matrix&); }} _c_{0};", name));
            self.emitln(&format!("inline int _d_{0}(Matrix& _a0, Matrix& _a1) {{", name));
            self.emitln("  uint64_t _k = ((uint64_t)_a0._vt->type_id) | ((uint64_t)_a1._vt->type_id << 16);");
            self.emitln(&format!("  if (_k == _c_{0}.k) [[likely]] return _c_{0}.fn(_a0, _a1);", name));
            self.emitln(&format!("  auto _it = _t_{0}.find(_k);", name));
            self.emitln(&format!("  if (_it != _t_{0}.end()) {{ _c_{0} = {{_k, _it->second}}; return _it->second(_a0, _a1); }}", name));
            self.emitln(&format!("  return {0}(_a0, _a1);", name));
            self.emitln("}");
            self.emitln("");
        }
    }

    fn emit_header(&mut self) {
        self.emitln("#pragma once");
        self.emitln("");
        self.emitln("// ─── Generated by Nova compiler ───");
        self.emitln("");
        self.emitln("#include <string>");
        self.emitln("#include <vector>");
        self.emitln("#include <memory>");
        self.emitln("#include <variant>");
        self.emitln("#include <optional>");
        self.emitln("#include <functional>");
        self.emitln("#include <unordered_map>");
        self.emitln("#include <iostream>");
        self.emitln("#include <cstdint>");
        self.emitln("inline void nova_print_int(int n) { std::cout << n << std::endl; }");
        self.emitln("");
    }

    fn emit_module(&mut self, module: &Module) {
        for item in &module.items {
            match item {
                Item::Struct(s) => self.emit_struct_decl(s),
                Item::Enum(e) => self.emit_enum_decl(e),
                _ => {}
            }
        }
        self.emitln("");
        for item in &module.items {
            match item {
                Item::Struct(s) => self.emit_struct_def(s),
                Item::Enum(e) => self.emit_enum_def(e),
                Item::Function(f) => {
                    // Track functions with multiple overloads for dispatch
                    let has_trait_params = f.params.iter().any(|p| {
                        if let Type::Path(ref path) = p.ty {
                            let n = path.segments.last().map(|s| s.name.as_str()).unwrap_or("");
                            n == "Matrix" // hardcoded for now; should check trait registry
                        } else { false }
                    });
                    if has_trait_params {
                        self.dispatch_needed.insert(f.name.clone());
                    }
                    // Emit forward decl for dispatch if needed
                    if self.dispatch_needed.contains(&f.name) {
                        self.emitln(&format!("int _d_{0}(Matrix&, Matrix&);", f.name));
                    }
                    self.emit_function(f);
                }
                Item::TypeAlias(a) => self.emit_type_alias(a),
                Item::VarDecl(vd) => self.emit_var_decl(vd),
                Item::Trait(t) => self.emit_trait(t),
                Item::Impl(imp) => self.emit_impl(imp),
                _ => {}
            }
        }
    }

    fn emit_function(&mut self, func: &Function) {
        self.return_trait = self.trait_name(&func.return_type);
        let ret = self.gen_type(&func.return_type);
        self.emit(&format!("{} {}(", ret, func.name));
        for (i, param) in func.params.iter().enumerate() {
            if i > 0 { self.emit(", "); }
            self.emit(&format!("{} {}", self.gen_type(&param.ty), param.name));
        }
        self.emitln(") {");
        self.indent_level += 1;
        let returns_value = !matches!(func.return_type, Type::Unit);
        self.emit_block(&func.body, returns_value);
        self.indent_level -= 1;
        self.emitln("}");
        self.emitln("");
    }

    fn emit_block(&mut self, block: &Block, in_expr_pos: bool) {
        for (i, stmt) in block.stmts.iter().enumerate() {
            let is_last = i == block.stmts.len() - 1;
            self.emit_stmt(stmt, is_last && in_expr_pos);
        }
    }

    fn emit_stmt(&mut self, expr: &Expr, is_tail: bool) {
        match &expr.kind {
            ExprKind::Block(b) => {
                self.emitln("{");
                self.indent_level += 1;
                self.emit_block(b, false);
                self.indent_level -= 1;
                self.emitln("}");
            }
            ExprKind::Let { name, ty, value, is_mut } => {
                let cpp_type = ty.as_ref().map(|t| self.gen_type(t)).unwrap_or_else(|| "auto".to_string());
                let val_str = self.gen_expr(value);
                self.emitln(&format!("auto {} = {};", name, val_str));
            }
            ExprKind::Return(opt) => {
                if let Some(ref e) = opt {
                    let val = self.coerce(&self.gen_expr(e));
                    self.emitln(&format!("return {};", val));
                } else {
                    self.emitln("return;");
                }
            }
            ExprKind::If { cond, then_branch, else_branch } => {
                let c = self.gen_expr(cond);
                self.emitln(&format!("if ({}) {{", c));
                self.indent_level += 1;
                self.emit_block(then_branch, is_tail);
                self.indent_level -= 1;
                if let Some(ref eb) = else_branch {
                    self.emitln("} else {");
                    self.indent_level += 1;
                    self.emit_block(eb, is_tail);
                    self.indent_level -= 1;
                }
                self.emitln("}");
            }
            ExprKind::Binary { op, left, right } => {
                let l = self.gen_expr(left);
                let r = self.gen_expr(right);
                if is_tail {
                    self.emitln(&format!("return ({} {} {});", l, op.cpp_op(), r));
                } else {
                    self.emitln(&format!("({} {} {});", l, op.cpp_op(), r));
                }
            }
            ExprKind::Call { func, args } => {
                // UFCS pattern
                if args.is_empty() {
                    if let ExprKind::Call { func: inner_func, args: inner_args } = &func.kind {
                        if let ExprKind::Ident(method) = &inner_func.kind {
                            if inner_args.len() == 1 {
                                let obj = self.gen_expr(&inner_args[0]);
                                if is_tail { self.emitln(&format!("return {}.{}();", obj, method)); }
                                else { self.emitln(&format!("{}.{}();", obj, method)); }
                                return;
                            }
                        }
                    }
                }
                let f = self.gen_expr(func);
                let a: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
                if self.dispatch_needed.contains(&f) {
                    if is_tail { self.emitln(&format!("return _d_{}({});", f, a.join(", "))); }
                    else { self.emitln(&format!("_d_{}({});", f, a.join(", "))); }
                } else {
                    if is_tail { self.emitln(&format!("return {}({});", f, a.join(", "))); }
                    else { self.emitln(&format!("{}({});", f, a.join(", "))); }
                }
            }
            _ => {
                let val = self.gen_expr(expr);
                if is_tail { self.emitln(&format!("return {};", val)); }
                else { self.emitln(&format!("{};", val)); }
            }
        }
    }

    fn gen_type(&self, ty: &Type) -> String {
        match ty {
            Type::Path(path) => {
                let name = path.segments.iter().map(|s| {
                    if s.args.is_empty() { self.map_primitive(&s.name).to_string() }
                    else { format!("{}<{}>", s.name, s.args.iter().map(|a| self.gen_type(a)).collect::<Vec<_>>().join(", ")) }
                }).collect::<Vec<_>>().join("::");
                name
            }
            Type::Unit => "void".to_string(),
            _ => "auto".to_string(),
        }
    }

    fn map_primitive<'a>(&self, name: &'a str) -> &'a str {
        match name {
            "Int" => "int", "Float" => "double", "Bool" => "bool", "Char" => "char",
            "String" => "std::string", _ => name,
        }
    }

    fn gen_expr(&self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::IntLiteral(n) => n.to_string(),
            ExprKind::FloatLiteral(n) => format!("{}", n),
            ExprKind::StringLiteral(s) => format!("\"{}\"", s),
            ExprKind::BoolLiteral(b) => if *b { "true".into() } else { "false".into() },
            ExprKind::Ident(name) => name.clone(),
            ExprKind::Field { object, field } => format!("{}.{}", self.gen_expr(object), field),
            ExprKind::Binary { op, left, right } => {
                format!("({} {} {})", self.gen_expr(left), op.cpp_op(), self.gen_expr(right))
            }
            ExprKind::Call { func, args } => {
                // UFCS: obj.method() or obj.method(args...)
                if let ExprKind::DotAccess { object, field } = &func.kind {
                    return format!("{}.{}({})", self.gen_expr(object), field,
                        args.iter().map(|a| self.gen_expr(a)).collect::<Vec<_>>().join(", "));
                }
                // Resolved UFCS: Call(Call(method, [obj]), [])
                if args.is_empty() {
                    if let ExprKind::Call { func: inner, args: inner_args } = &func.kind {
                        if let ExprKind::Ident(method) = &inner.kind {
                            if inner_args.len() == 1 {
                                return format!("{}.{}()", self.gen_expr(&inner_args[0]), method);
                            }
                        }
                    }
                }
                let f = self.gen_expr(func);
                let a: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
                if self.dispatch_needed.contains(&f) {
                    format!("_d_{}({})", f, a.join(", "))
                } else {
                    self.maybe_ufcs(&f, &a)
                }
            }
            ExprKind::StructLit { path, fields } => {
                let tn = path.join("::");
                let args: Vec<String> = fields.iter().map(|(_, v)| self.gen_expr(v)).collect();
                format!("{} {{ {} }}", tn, args.join(", "))
            }
            ExprKind::DotAccess { object, field } => format!("{}.{}", self.gen_expr(object), field),
            _ => format!("/* {:?} */", expr.kind),
        }
    }

    fn emit_struct_decl(&mut self, s: &Struct) {
        self.emitln(&format!("// struct {};", s.name));
    }

    fn emit_struct_def(&mut self, s: &Struct) {
        self.emitln(&format!("struct {} {{", s.name));
        for field in &s.fields {
            self.emitln(&format!("  {} {};", self.gen_type(&field.ty), field.name));
        }
        let args: Vec<String> = s.fields.iter().map(|f| format!("{} {}", self.gen_type(&f.ty), f.name)).collect();
        let inits: Vec<String> = s.fields.iter().map(|f| format!("{}({})", f.name, f.name)).collect();
        self.emitln(&format!("  {}({}) : {} {{}}", s.name, args.join(", "), inits.join(", ")));
        self.emitln("};");
        self.emitln("");
    }

    fn emit_trait(&mut self, t: &TraitDef) {
        use crate::traits::TraitRegistry;
        let mut reg = TraitRegistry::new();
        reg.register_trait(crate::traits::TraitInfo {
            name: t.name.clone(),
            generics: t.generics.iter().map(|g| g.name.clone()).collect(),
            methods: t.methods.clone(),
        });
        self.emit(&reg.codegen_trait_decl(&t.name));
    }

    fn emit_impl(&mut self, imp: &ImplBlock) {
        use crate::traits::{TraitInfo, TraitRegistry};
        let mut reg = TraitRegistry::new();
        // Register trait info first (needed for vtable generation)
        // The trait definition should be in the module items
        for item in &[] as &[Item] {} // placeholder — need module access
        let target_name = match &imp.target_type {
            Type::Path(p) => p.segments.last().map(|s| s.name.as_str()).unwrap_or("unknown"),
            _ => "unknown",
        };
        self.emit(&format!("// impl {} for {}\n", imp.trait_name, target_name));
        self.emit(&format!("inline Matrix as_Matrix({}* p) {{ return {{ p, nullptr }}; }}\n", target_name));
        self.emitln("");
    }

    fn emit_type_alias(&mut self, _a: &TypeAlias) {}
    fn emit_var_decl(&mut self, _vd: &VarDecl) {}
    fn emit_enum_decl(&mut self, _e: &Enum) {}
    fn emit_enum_def(&mut self, _e: &Enum) {}

    fn emit(&mut self, s: &str) { self.output.push_str(s); }
    fn emitln(&mut self, s: &str) {
        for _ in 0..self.indent_level { self.output.push_str("  "); }
        self.output.push_str(s);
        self.output.push('\n');
    }
    fn trait_name(&self, ty: &Type) -> Option<String> {
        match ty {
            Type::Path(ref p) => {
                let n = p.segments.last().map(|s| s.name.as_str()).unwrap_or("");
                match n { "Int" | "Float" | "Bool" | "String" | "Char" | "void" => None, _ => Some(n.to_string()) }
            }
            _ => None,
        }
    }
    fn coerce(&self, expr_str: &str) -> String {
        match &self.return_trait {
            Some(t) => format!("as_{}(new {})", t, expr_str),
            None => expr_str.to_string(),
        }
    }
    fn maybe_ufcs(&self, f: &str, args: &[String]) -> String {
        if args.len() == 1 && (f == "size" || f == "get") {
            return format!("{}.{}()", args[0], f);
        }
        if self.dispatch_needed.contains(f) {
            format!("_d_{}({})", f, args.join(", "))
        } else {
            format!("{}({})", f, args.join(", "))
        }
    }
    fn map_runtime_call(fn map_runtime_call(&self, name: &str) -> &strself, name: &str) -> String { match name { "print".into(), "print_int".into(), _ => name.to_string() } }
}
