use crate::ast::*;
use crate::token::Span;
use std::collections::{HashMap, HashSet};

pub struct CppGenerator {
    output: String,
    indent: usize,
    dispatch: HashMap<String, usize>,  // name → arity
    return_trait: Option<String>,
    trait_methods: HashSet<String>,
    type_ids: HashMap<String, u32>,
}

impl CppGenerator {
    pub fn new() -> Self {
        Self {
            output: String::new(), indent: 0, dispatch: HashMap::new(),
            return_trait: None, trait_methods: HashSet::new(), type_ids: HashMap::new(),
        }
    }

    pub fn generate(mut self, module: &Module) -> String {
        self.collect_info(module);
        self.emit_header();
        self.emit_module(module);
        self.emit_dispatch_wrappers();
        self.output
    }

    fn collect_info(&mut self, module: &Module) {
        let trait_names: HashSet<String> = module.items.iter()
            .filter_map(|item| if let Item::Trait(t) = item { Some(t.name.clone()) } else { None })
            .collect();
        // First pass: count all function/method names
        let mut counts: HashMap<String, usize> = HashMap::new();
        for item in &module.items {
            if let Item::Function(f) = item { *counts.entry(f.name.clone()).or_default() += 1; }
            if let Item::Impl(imp) = item {
                for m in &imp.methods { *counts.entry(m.name.clone()).or_default() += 1; }
            }
        }
        // Second pass: determine which need dispatch (any arity!)
        for item in &module.items {
            if let Item::Function(f) = item {
                self.check_dispatch(f, &trait_names, &counts);
            }
            if let Item::Impl(imp) = item {
                for m in &imp.methods { self.check_dispatch(m, &trait_names, &counts); }
            }
            if let Item::Trait(t) = item {
                if t.name != "Debug" {
                    for m in &t.methods { self.trait_methods.insert(m.name.clone()); }
                }
            }
        }
    }

    fn check_dispatch(&mut self, f: &Function, trait_names: &HashSet<String>, counts: &HashMap<String, usize>) {
        let has_trait_param = f.params.iter().any(|p| {
            if let Type::Path(ref path) = p.ty {
                trait_names.contains(path.segments.last().map(|s| s.name.as_str()).unwrap_or(""))
            } else { false }
        });
        let overloaded = *counts.get(&f.name).unwrap_or(&0) > 1;
        if has_trait_param && overloaded && f.return_type.to_string() != "void" {
            let arity = f.params.iter().filter(|p| {
                if let Type::Path(ref path) = p.ty {
                    trait_names.contains(path.segments.last().map(|s| s.name.as_str()).unwrap_or(""))
                } else { false }
            }).count();
            // Keep the maximum arity across overloads
            let existing = self.dispatch.get(&f.name).copied().unwrap_or(0);
            self.dispatch.insert(f.name.clone(), arity.max(existing));
        }
    }

    fn is_primitive(path: &Path) -> bool {
        let n = path.segments.last().map(|s| s.name.as_str()).unwrap_or("");
        matches!(n, "Int" | "Float" | "Bool" | "String" | "Char" | "void")
    }

    fn emit_header(&mut self) {
        self.emitln("#pragma once\n// ─── Generated by Nova compiler ───");
        self.emitln("#include <string>");
        self.emitln("#include <vector>");
        self.emitln("#include <memory>");
        self.emitln("#include <unordered_map>");
        self.emitln("#include <iostream>");
        self.emitln("#include <cstdint>");
        self.emitln("inline void nova_print_int(int n) { std::cout << n << std::endl; }");
        self.emitln("inline void nova_print(const std::string& s) { std::cout << s; }");
        self.emitln("template<typename T> void nova_print(T v) { std::cout << v; }");
        self.emitln("");
    }

    fn emit_module(&mut self, module: &Module) {
        for item in &module.items {
            match item {
                Item::Struct(s) => self.emit_struct(s),
                Item::Trait(t) => self.emit_trait(t),
                Item::Impl(imp) => self.emit_impl(imp),
                _ => {}
            }
        }
        for (name, arity) in self.dispatch.clone() {
            let sig = if arity == 1 { "Matrix&".to_string() } else { "Matrix&, Matrix&".to_string() };
            self.emitln(&format!("int _d_{}({});", name, sig));
        }
        for item in &module.items {
            if let Item::Function(f) = item { self.emit_function(f); }
        }
    }

    fn emit_struct(&mut self, s: &Struct) {
        self.emitln(&format!("struct {} {{", s.name));
        for field in &s.fields {
            self.emitln(&format!("  {} {};", self.gen_type(&field.ty), field.name));
        }
        let args: Vec<String> = s.fields.iter().map(|f| format!("{} {}", self.gen_type(&f.ty), f.name)).collect();
        let inits: Vec<String> = s.fields.iter().map(|f| format!("{}({})", f.name, f.name)).collect();
        if !args.is_empty() {
            self.emitln(&format!("  {}({}) : {} {{}}", s.name, args.join(", "), inits.join(", ")));
        }
        self.emitln("};");
        self.emitln("");
    }

    fn emit_trait(&mut self, t: &TraitDef) {
        self.emitln(&format!("// ─── trait {} ───", t.name));
        self.emitln(&format!("struct {}_vtable {{", t.name));
        self.emitln("  uint32_t type_id;");
        for m in &t.methods {
            let ret = self.gen_type(&m.return_type);
            let params: Vec<String> = m.params.iter().skip(1).map(|p| format!("{} {}", self.gen_type(&p.ty), p.name)).collect();
            self.emitln(&format!("  {} (*{})(void*{});", ret, m.name, if params.is_empty() { "".into() } else { format!(", {}", params.join(", ")) }));
        }
        self.emitln("};");
        self.emitln(&format!("struct {} {{", t.name));
        self.emitln("  void* _ptr;");
        self.emitln(&format!("  {}_vtable* _vt;", t.name));
        for m in &t.methods {
            let ret = self.gen_type(&m.return_type);
            let pn: Vec<String> = m.params.iter().skip(1).map(|p| p.name.clone()).collect();
            let pd: Vec<String> = m.params.iter().skip(1).map(|p| format!("{} {}", self.gen_type(&p.ty), p.name)).collect();
            self.emitln(&format!("  {} {}({}) {{ return _vt->{}(_ptr{}); }}", ret, m.name, pd.join(", "), m.name, if pn.is_empty() { "".into() } else { format!(", {}", pn.join(", ")) }));
        }
        self.emitln("};");
        self.emitln("");
    }

    fn emit_impl(&mut self, imp: &ImplBlock) {
        let target = match &imp.target_type {
            Type::Path(p) => p.segments.last().map(|s| s.name.as_str()).unwrap_or("unknown"),
            _ => "unknown",
        };
        let trait_name = &imp.trait_name;
        let type_id: u32 = target.bytes().fold(1u32, |h, b| h.wrapping_mul(31).wrapping_add(b as u32)) % 65535 + 1;
        self.type_ids.insert(target.to_string(), type_id);
        self.emitln(&format!("// impl {} for {} (id={})", trait_name, target, type_id));
        for method in &imp.methods {
            let ret = self.gen_type(&method.return_type);
            let params: Vec<String> = std::iter::once("void* self".to_string())
                .chain(method.params.iter().skip(1).map(|p| format!("{} {}", self.gen_type(&p.ty), p.name)))
                .collect();
            // Use self_ptr to avoid conflict with the casted self variable
            let params_str = params.join(", ").replace("void* self", "void* self_ptr");
            let first_param = method.params.first().map(|p| p.name.clone()).unwrap_or_else(|| "self".into());
            // Generate impl function with concrete type (not void*)
            let mut impl_params: Vec<String> = method.params.iter()
                .map(|p| format!("{} {}", self.gen_type(&p.ty), p.name)).collect();
            self.emit(&format!("inline {} {}__{}({}) {{", ret, target, method.name, impl_params.join(", ")));
            self.indent += 1;
            self.emit_block(&method.body, !matches!(method.return_type, Type::Unit) && self.gen_type(&method.return_type) != "void");
            self.indent -= 1;
            self.emitln("}");
            // Vtable trampoline: void* → concrete
            self.emit(&format!("inline {} {}__{}_vt(void* self", ret, target, method.name));
            for p in method.params.iter().skip(1) {
                self.emit(&format!(", {} {}", self.gen_type(&p.ty), p.name));
            }
            self.emit(&format!(") {{ return {}__{}(*({}*)self", target, method.name, target));
            for p in method.params.iter().skip(1) {
                self.emit(&format!(", {}", p.name));
            }
            self.emitln("); }");
        }
        self.emitln(&format!("inline {}_vtable __vt_{}_{} = {{", trait_name, trait_name, target));
        self.emitln(&format!("  {},", type_id));
        for method in &imp.methods {
            self.emitln(&format!("  (decltype({}_vtable::{}))&{}__{}_vt,", trait_name, method.name, target, method.name));
        }
        self.emitln("};");
        self.emitln(&format!("inline {} as_{}({}* p) {{ return {{ p, &__vt_{}_{} }}; }}", trait_name, trait_name, target, trait_name, target));
        // Generate free function wrappers for UFCS
        for method in &imp.methods {
            let ret = self.gen_type(&method.return_type);
            let params: Vec<String> = method.params.iter().map(|p| format!("{} {}", self.gen_type(&p.ty), p.name)).collect();
            self.emit(&format!("inline {} {}({}) {{", ret, method.name, params.join(", ")));
            self.emit(&format!(" return {}__{}(", target, method.name));
            let args: Vec<String> = method.params.iter().map(|p| p.name.clone()).collect();
            self.emit(&format!("{}); }}", args.join(", ")));
        }
        self.emitln("");
    }

    fn emit_function(&mut self, func: &Function) {
        self.return_trait = self.trait_name(&func.return_type);
        let ret = self.gen_type(&func.return_type);
        let params: Vec<String> = func.params.iter().map(|p| format!("{} {}", self.gen_type(&p.ty), p.name)).collect();
        self.emitln(&format!("{} {}({}) {{", ret, func.name, params.join(", ")));
        self.indent += 1;
        self.emit_block(&func.body, !matches!(func.return_type, Type::Unit) && self.gen_type(&func.return_type) != "void");
        self.indent -= 1;
        self.emitln("}");
        self.emitln("");
        self.return_trait = None;
    }

    fn emit_block(&mut self, block: &Block, in_expr_pos: bool) {
        for (i, stmt) in block.stmts.iter().enumerate() {
            self.emit_stmt(stmt, i == block.stmts.len() - 1 && in_expr_pos);
        }
    }

    fn emit_stmt(&mut self, expr: &Expr, is_tail: bool) {
        match &expr.kind {
            ExprKind::Return(Some(e)) => {
                let v = self.coerce(&self.gen_expr(e));
                self.emitln(&format!("return {};", v));
            }
            ExprKind::Return(None) => self.emitln("return;"),
            ExprKind::Let { name, value, .. } => {
                self.emitln(&format!("auto {} = {};", name, self.gen_expr(value)));
            }
            ExprKind::If { cond, then_branch, else_branch } => {
                self.emitln(&format!("if ({}) {{", self.gen_expr(cond)));
                self.indent += 1; self.emit_block(then_branch, is_tail); self.indent -= 1;
                if let Some(eb) = else_branch {
                    self.emitln("} else {");
                    self.indent += 1; self.emit_block(eb, is_tail); self.indent -= 1;
                }
                self.emitln("}");
            }
            ExprKind::Binary { op, left, right } => {
                let s = format!("({} {} {})", self.gen_expr(left), op.cpp_op(), self.gen_expr(right));
                if is_tail { self.emitln(&format!("return {};", s)); } else { self.emitln(&format!("{};", s)); }
            }
            _ => {
                let v = self.gen_expr(expr);
                if is_tail { self.emitln(&format!("return {};", v)); } else { self.emitln(&format!("{};", v)); }
            }
        }
    }

    fn call_name(&self, func: &Expr, args: &[String]) -> String {
        let f = self.gen_expr(func);
        let name = if let ExprKind::Ident(n) = &func.kind { n.clone() } else { f.clone() };
        let mapped = self.map_runtime(&name);
        // Trait vtable methods → obj.method()
        if args.len() == 1 && self.trait_methods.contains(&name) {
            return format!("{}.{}()", args[0], name);
        }
        if self.dispatch.contains_key(&name) {
            format!("_d_{}({})", name, args.join(", "))
        } else {
            format!("{}({})", mapped, args.join(", "))
        }
    }

    fn gen_expr(&self, expr: &Expr) -> String {
        match &expr.kind {
            ExprKind::IntLiteral(n) => n.to_string(),
            ExprKind::FloatLiteral(n) => format!("{}", n),
            ExprKind::StringLiteral(s) => format!("\"{}\"", s),
            ExprKind::BoolLiteral(b) => if *b { "true".into() } else { "false".into() },
            ExprKind::Ident(name) => name.clone(),
            ExprKind::Field { object, field } => format!("{}.{}", self.gen_expr(object), field),
            ExprKind::DotAccess { object, field } => format!("{}.{}", self.gen_expr(object), field),
            ExprKind::Binary { op, left, right } =>
                format!("({} {} {})", self.gen_expr(left), op.cpp_op(), self.gen_expr(right)),
            ExprKind::Call { func, args } => {
                let a: Vec<String> = args.iter().map(|a| self.gen_expr(a)).collect();
                self.call_name(func, &a)
            }
            ExprKind::StructLit { path, fields } => {
                let tn = path.join("::");
                let vals: Vec<String> = fields.iter().map(|(_, v)| self.gen_expr(v)).collect();
                format!("{} {{ {} }}", tn, vals.join(", "))
            }
            _ => format!("/* {:?} */", expr.kind),
        }
    }

    fn gen_type(&self, ty: &Type) -> String {
        match ty {
            Type::Path(p) => p.segments.iter().map(|s| {
                if s.args.is_empty() { self.map_primitive(&s.name).to_string() }
                else { format!("{}<{}>", s.name, s.args.iter().map(|a| self.gen_type(a)).collect::<Vec<_>>().join(", ")) }
            }).collect::<Vec<_>>().join("::"),
            Type::Unit => "void".to_string(),
            _ => "auto".to_string(),
        }
    }

    fn map_primitive<'a>(&self, name: &'a str) -> &'a str {
        match name { "Int" => "int", "Float" => "double", "Bool" => "bool", "Char" => "char", "String" => "std::string", _ => name }
    }

    fn map_runtime(&self, name: &str) -> String {
        match name { "print" => "nova_print".into(), "print_int" => "nova_print_int".into(), _ => name.to_string() }
    }

    fn trait_name(&self, ty: &Type) -> Option<String> {
        match ty { Type::Path(p) if !Self::is_primitive(p) => Some(p.segments.last().unwrap().name.clone()), _ => None }
    }

    fn coerce(&self, expr: &str) -> String {
        match &self.return_trait { Some(t) => format!("as_{}(new {})", t, expr), None => expr.to_string() }
    }

    fn emit_dispatch_wrappers(&mut self) {
        let type_ids: Vec<(String, u32)> = self.type_ids.iter().map(|(k,v)| (k.clone(), *v)).collect();
        for (name, arity) in self.dispatch.clone() {
            let mat_refs: Vec<String> = (0..arity).map(|_| "Matrix&".to_string()).collect();
            let sig = mat_refs.join(", ");
            let args: Vec<String> = (0..arity).map(|i| format!("Matrix& a{}", i)).collect();
            let names: Vec<String> = (0..arity).map(|i| format!("a{}", i)).collect();
            
            self.emitln(&format!("static std::unordered_map<uint64_t, int(*)({})> _t_{};", sig, name));
            self.emitln(&format!("static struct {{ uint64_t k=UINT64_MAX; int(*fn)({}); }} _c_{};", sig, name));
            self.emitln(&format!("static struct _Reg_{0} {{ _Reg_{0}() {{", name));
            
            if arity == 1 {
                for (t1, id1) in &type_ids {
                    let key = *id1 as u64;
                    self.emitln(&format!("  _t_{}[{}ULL] = []({}) {{ return {}({}); }};", name, key, args[0], name, names[0]));
                }
            } else {
                for (t1, id1) in &type_ids {
                    for (t2, id2) in &type_ids {
                        let key = (*id1 as u64) | ((*id2 as u64) << 16);
                        self.emitln(&format!("  _t_{}[{}ULL] = []({}, {}) {{ return {}({}, {}); }};", name, key, args[0], args[1], name, names[0], names[1]));
                    }
                }
            }
            
            self.emitln(&format!("  }}}}; static _Reg_{0} _reg_{0};", name));
            
            self.emitln(&format!("inline int _d_{}({}) {{", name, args.join(", ")));
            self.emit("  uint64_t k = ");
            for (i, _) in names.iter().enumerate() {
                if i > 0 { self.emit(" | "); }
                self.emit(&format!("((uint64_t)a{}._vt->type_id << {})", i, i * 16));
            }
            self.emitln(";");
            self.emitln(&format!("  if (k == _c_{0}.k) [[likely]] return _c_{0}.fn({1});", name, names.join(", ")));
            self.emitln(&format!("  auto it = _t_{}.find(k);", name));
            self.emitln(&format!("  if (it != _t_{}.end()) {{ _c_{0} = {{k, it->second}}; return it->second({1}); }}", name, names.join(", ")));
            self.emitln(&format!("  return {}({});", name, names.join(", ")));
            self.emitln("}");
            self.emitln("");
        }
    }

    fn emit(&mut self, s: &str) { self.output.push_str(s); }
    fn emitln(&mut self, s: &str) {
        for _ in 0..self.indent { self.output.push_str("  "); }
        self.output.push_str(s); self.output.push('\n');
    }
}
